apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zenapi
  template:
    metadata:
      labels:
        app: zenapi
    spec:
      containers:
      - name: zenapi
        image: liu149/zenapi-app:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: zenapi-service
spec:
  selector:
    app: zenapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer