apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
      annotations:
        iam.gke.io/gcp-service-account: external-dns@bamboo-zephyr-435715-f7.iam.gserviceaccount.com
    spec:
      serviceAccountName: external-dns  # 这里指定使用我们创建的 ServiceAccount
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.12.0
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=fisherman.top # 将这里替换为您的域名
        - --zone-id-filter=fisherman-top
        - --provider=google
        - --google-project=bamboo-zephyr-435715-f7 # 将这里替换为您的 GCP 项目 ID
        - --registry=txt
        - --txt-owner-id=default
        - --log-level=debug  # 增加日志级别
        - --log-format=json  # 使用 JSON 格式输出日志
        - --interval=30s     # 减少同步间隔，以便更快看到结果
        - --google-zone-visibility=public  # 明确指定使用公共 DNS 区域