apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenapi-gke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenapi-gke
  template:
    metadata:
      labels:
        app: zenapi-gke
    spec:
      containers:
      - name: zenapi
        image: gcr.io/PROJECT_ID/zenapi-app:TAG  # This will be replaced by the sed command
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: zenapi-gke-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.fisherman.top  # 替换为您想要的域名
spec:
  selector:
    app: zenapi-gke
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # 使用 LoadBalancer 类型以获得外部 IP