apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenapi-gke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenapi-gke
  template:
    metadata:
      labels:
        app: zenapi-gke
    spec:
      containers:
      - name: zenapi
        image: gcr.io/PROJECT_ID/zenapi-app:TAG  # This will be replaced by the sed command
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: zenapi-gke-service
spec:
  selector:
    app: zenapi-gke
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # 改为 ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zenapi-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    external-dns.alpha.kubernetes.io/hostname: api.fisherman.top
spec:
  rules:
  - host: api.fisherman.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zenapi-gke-service
            port: 
              number: 80