apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenapi-gke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenapi-gke
  template:
    metadata:
      labels:
        app: zenapi-gke
    spec:
      containers:
      - name: zenapi
        image: gcr.io/PROJECT_ID/zenapi-app:TAG  # This will be replaced by the sed command
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: database
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "5432"
        - name: USE_CLOUD_SQL_PROXY
          value: "true"
        - name: INSTANCE_CONNECTION_NAME
          value: "PROJECT_ID:REGION:INSTANCE_NAME"
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
        command:
          - "/cloud_sql_proxy"
          - "-instances=PROJECT_ID:REGION:INSTANCE_NAME=tcp:5432"
        securityContext:
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: zenapi-gke-service
spec:
  selector:
    app: zenapi-gke
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # 改为 ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zenapi-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    external-dns.alpha.kubernetes.io/hostname: api.fisherman.top
spec:
  rules:
  - host: api.fisherman.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zenapi-gke-service
            port: 
              number: 80